Style/StringLiterals:
  EnforcedStyle: single_quotes

AllCops:
  Exclude:
    - 'tmp/**/*'
  TargetRubyVersion: 2.3
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/DotPosition:
  Description: 'Checks the position of the dot in multi-line method call'
  EnforcedStyle: leading

Style/Documentation:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Metrics/LineLength:
  Max: 90
Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/**/*
    - features/step_definitions/*
Metrics/ModuleLength:
  Enabled: true
  Exclude: 
    - spec/**/*
    - features/step_definitions/*
Metrics/MethodLength:
  Enabled: true
  Max: 15
  Exclude: 
    - spec/**/*
    - features/step_definitions/*    