CREATE TABLE "schema_migrations" ("version" varchar NOT NULL);
CREATE UNIQUE INDEX "unique_schema_migrations" ON "schema_migrations" ("version");
CREATE TABLE "addresses" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "street" varchar, "city" varchar, "zipcode" varchar, "location_id" integer, "location_type" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE INDEX "index_addresses_on_location_type_and_location_id" ON "addresses" ("location_type", "location_id");
CREATE TABLE "skills" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "description" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "email" varchar DEFAULT '' NOT NULL, "first_name" varchar, "last_name" varchar, "phone" varchar, "actable_id" integer, "actable_type" varchar, "encrypted_password" varchar DEFAULT '' NOT NULL, "reset_password_token" varchar, "reset_password_sent_at" datetime, "remember_created_at" datetime, "sign_in_count" integer DEFAULT 0 NOT NULL, "current_sign_in_at" datetime, "last_sign_in_at" datetime, "current_sign_in_ip" varchar, "last_sign_in_ip" varchar, "confirmation_token" varchar, "confirmed_at" datetime, "confirmation_sent_at" datetime, "unconfirmed_email" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE INDEX "index_users_on_email" ON "users" ("email");
CREATE UNIQUE INDEX "index_users_on_reset_password_token" ON "users" ("reset_password_token");
CREATE TABLE "companies" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "ein" varchar, "phone" varchar, "email" varchar, "website" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "company_people" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "company_id" integer, "address_id" integer, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE INDEX "index_company_people_on_company_id" ON "company_people" ("company_id");
CREATE INDEX "index_company_people_on_address_id" ON "company_people" ("address_id");
CREATE TABLE "job_categories" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "description" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "jobs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar, "description" varchar, "company_id" integer, "company_person_id" integer, "job_category_id" integer, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE INDEX "index_jobs_on_company_id" ON "jobs" ("company_id");
CREATE INDEX "index_jobs_on_company_person_id" ON "jobs" ("company_person_id");
CREATE INDEX "index_jobs_on_job_category_id" ON "jobs" ("job_category_id");
CREATE TABLE "job_seeker_statuses" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "value" varchar, "description" text, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "job_seekers" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "year_of_birth" varchar, "job_seeker_status_id" integer, "resume" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE INDEX "index_job_seekers_on_job_seeker_status_id" ON "job_seekers" ("job_seeker_status_id");
CREATE TABLE "seekers_agency_people" ("agency_person_id" integer, "job_seeker_id" integer);
CREATE INDEX "seekersagencypeople" ON "seekers_agency_people" ("agency_person_id", "job_seeker_id");
CREATE TABLE "agencies" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "website" varchar, "phone" varchar, "email" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "agencies_companies" ("agency_id" integer NOT NULL, "company_id" integer NOT NULL);
CREATE TABLE "agency_people" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "agency_id" integer, "address_id" integer, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE INDEX "index_agency_people_on_agency_id" ON "agency_people" ("agency_id");
CREATE INDEX "index_agency_people_on_address_id" ON "agency_people" ("address_id");
CREATE TABLE "skill_levels" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "description" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "job_skills" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "job_id" integer, "skill_id" integer, "skill_level_id" integer, "required" boolean DEFAULT 'f', "min_years" integer, "max_years" integer, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE INDEX "index_job_skills_on_job_id" ON "job_skills" ("job_id");
CREATE INDEX "index_job_skills_on_skill_id" ON "job_skills" ("skill_id");
CREATE INDEX "index_job_skills_on_skill_level_id" ON "job_skills" ("skill_level_id");
CREATE TABLE "job_categories_skills" ("job_category_id" integer NOT NULL, "skill_id" integer NOT NULL);
CREATE TABLE "agency_roles" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "role" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "agency_people_roles" ("agency_person_id" integer NOT NULL, "agency_role_id" integer NOT NULL);
CREATE TABLE "job_specialities" ("agency_person_id" integer NOT NULL, "job_category_id" integer NOT NULL);
CREATE TABLE "company_roles" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "role" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "company_people_roles" ("company_person_id" integer, "company_role_id" integer);
INSERT INTO schema_migrations (version) VALUES ('20151107120000');

